units_type: character
feature_source: kaldi
feature_type: mfcc
data:
    name: thchs30
    vocab: /home/oshindo/kaldi/egs/thchs30/s5/data/lang_phone/phones.txt
    left_context_width: 0
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: False
    max_input_length: 2000
    max_target_length: 200
    batch_size: 4
    short_first: True
    shuffle: False
    train: /home/oshindo/kaldi/egs/thchs30/s5/data/mfcc/train
    dev: /home/oshindo/kaldi/egs/thchs30/s5/data/mfcc/dev
    test: /home/oshindo/kaldi/egs/thchs30/s5/data/mfcc/test
model:
    type: transducer
    enc:
        type: attention
        hidden_size: 39
        output_size: 320
        d_inner: 39
        n_head: 3
        d_model: 39
        d_head: 13
        n_layer: 4
    dec:
        type: attention
        hidden_size: 39
        output_size: 320
        d_inner: 39
        n_head: 3
        d_model: 39
        d_head: 13
        n_layer: 1
    joint:
        input_size: 640
        inner_size: 512
    vocab_size: 219
    share_weight: False
    feature_dim: 39
    dropout: 0.1
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2020
    num_gpu: 1
    epochs: 60
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: 4enc_1dec_512joint
optim:
    type: sgd
    lr: 0.0001
    momentum: 0.9
    decay_ratio: 0.5
    weight_decay: 0
    begin_to_adjust_lr: 10
