units_type: character
feature_source: kaldi
feature_type: fbank
data:
    name: thchs30
    vocab: thchs30_phone_table.txt
    left_context_width: 3
    right_context_width: 0
    frame_rate: 30
    apply_cmvn: False
    max_input_length: 521
    max_target_length: 94
    batch_size: 3
    short_first: True
    shuffle: False
    train: /home/oshindo/kaldi/egs/thchs30/s5/data/train
    dev: /home/oshindo/kaldi/egs/thchs30/s5/data/dev
    test: /home/oshindo/kaldi/egs/thchs30/s5/data/test
model:
    type: transducer
    enc:
        type: attention
        hidden_size:
        output_size:
        d_inner: 320
        n_head: 8
        d_model: 160
        d_head: 20
        n_layer: 4
    dec:
        type: attention
        hidden_size:
        output_size:
        d_inner: 320
        n_head: 3
        d_model: 213
        d_head: 71
        n_layer: 1
    joint:
        input_size: 373
        inner_size: 512
    vocab_size: 213
    share_weight: False
    feature_dim:
    dropout: 0.1
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2020
    num_gpu: 1
    epochs: 20
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: 4enc_1dec_512joint
optim:
    type: sgd
    lr: 0.0001
    momentum: 0.9
    decay_ratio: 0.5
    weight_decay: 0
    begin_to_adjust_lr: 10
